#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# One-time setup: give CI the credentials to submit a release to the
# Microsoft Store by itself. See docs/agents/releases.md.
#
# This comes after scripts/store_setup_wizard.sh, not instead of it. The
# submission API can only update an app whose first submission a human has
# already made, so Cadent has to be in the Store before any of this works.
#
# A separate app registration from the signing one, on purpose: that identity
# can sign and nothing else, this one can publish and nothing else.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

REPO_SLUG="mikeallisonJS/cadent"
PARTNER_CENTER="https://partner.microsoft.com/dashboard"

# gh reads this wherever a command takes no --repo, which includes the
# library's `gh secret set`. Without it a fork checkout would receive the
# secrets while stage 7 checked for them here.
export GH_REPO="$REPO_SLUG"

banner "Cadent — Microsoft Store submission API"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  printf '  %s✓%s gh is installed and authenticated\n' "$GREEN" "$RESET"
else
  warn "gh is missing or not logged in — run: gh auth login"
  note "Without it, stage 7 leaves the five secrets for you to set by hand."
  confirm "Continue anyway?" || { say "Fix the above and re-run."; exit 0; }
fi
say ""
say "Two things have to be true already, and this wizard can't make them so:"
step "Cadent has been submitted to the Store once, by hand, in Partner Center."
step "You can sign in to Partner Center as the account owner or a Manager."
note "The API updates an existing app. It cannot create one, or its first"
note "submission — that is scripts/store_setup_wizard.sh, stage 10."
confirm "Both true?" || { say "Do the first submission, then re-run."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Partner Center — associate the Entra tenant"
say "The API authenticates through Microsoft Entra, so Partner Center has to"
say "know which tenant to trust."
open_url "$PARTNER_CENTER/account/v3/tenantmanagement"
step "Account settings (gear, top right) > Tenants."
step "If a tenant is already listed, there is nothing to do here."
step "Otherwise: Associate Microsoft Entra ID, and sign in as a Global"
step "  Administrator of the tenant — the one holding the signing account is fine."
note "No tenant at all? 'Create Microsoft Entra ID' on the same page makes one"
note "at no charge."
note "Partner Center's navigation moves around. If the link lands somewhere"
note "else, the page you want is called 'Tenants' under Account settings."
pause "Press Enter once a tenant is associated"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Partner Center — the application CI signs in as"
open_url "$PARTNER_CENTER/account/v3/usermanagement"
step "Account settings > User management > Microsoft Entra applications."
step "Add Microsoft Entra application > Create Microsoft Entra application."
step "Name it something like 'cadent-ci-store'. Reply URL and App ID URI can be"
step "  any URL you own; nothing here ever visits them."
step "Role: Manager. The API refuses anything less."
step "Save. The confirmation page shows a Tenant ID and a Client ID."
ask STORE_TENANT_ID "Tenant ID:"
ask STORE_CLIENT_ID "Client ID:"
write_env STORE_TENANT_ID "$STORE_TENANT_ID"
write_env STORE_CLIENT_ID "$STORE_CLIENT_ID"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Entra — a client secret"
say "Made in the Azure portal, where you choose when it expires."
open_url "https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
step "All applications > the one you just created > Certificates & secrets."
step "Client secrets > New client secret."
step "Copy the VALUE column, not the Secret ID — the value is shown once."
warn "Note the expiry you chose. When it lapses, the release still ships but the"
warn "Store job fails at login; the fix is a new secret here and a re-run of this"
warn "wizard."
ask_secret STORE_CLIENT_SECRET "Client secret value:"
write_env STORE_CLIENT_SECRET "$STORE_CLIENT_SECRET"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Partner Center — seller ID"
open_url "$PARTNER_CENTER/account/v3/organization/legalinfo"
step "Account settings > Legal info (older layouts: Organization profile)."
step "Copy the Seller ID — a number, usually eight digits."
note "Not the Publisher ID and not the tenant ID: the API takes this one as its"
note "X-Seller-Account-Id header and refuses either of the others."
ask STORE_SELLER_ID "Seller ID:"
write_env STORE_SELLER_ID "$STORE_SELLER_ID"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Partner Center — Cadent's product ID"
open_url "$PARTNER_CENTER/apps-and-games/overview"
step "Open Cadent > Product management > Product identity."
step "Copy the Store ID. For an EXE app it is fourteen characters and starts"
step "  with XP."
note "It is also the last path segment of the app's Store link,"
note "apps.microsoft.com/detail/<this>."
ask STORE_PRODUCT_ID "Store ID:"
if [[ ! "$STORE_PRODUCT_ID" =~ ^[Xx][Pp] ]]; then
  warn "that doesn't start with XP. MSI/EXE apps get XP... ids, and the API this"
  warn "automation uses only handles those — check you copied the Store ID."
  confirm "Keep it anyway?" || ask STORE_PRODUCT_ID "Store ID:"
fi
write_env STORE_PRODUCT_ID "$STORE_PRODUCT_ID"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub — the five Store secrets"
say "store-submit.yml reads all five or none. A partial set fails the job on"
say "purpose, so a release never silently skips the Store."
set_secret STORE_TENANT_ID     "$STORE_TENANT_ID"
set_secret STORE_CLIENT_ID     "$STORE_CLIENT_ID"
set_secret STORE_CLIENT_SECRET "$STORE_CLIENT_SECRET"
set_secret STORE_SELLER_ID     "$STORE_SELLER_ID"
set_secret STORE_PRODUCT_ID    "$STORE_PRODUCT_ID"

say ""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "What the repo has now:"
  gh secret list --repo "$REPO_SLUG" 2>/dev/null | grep '^STORE_' || \
    warn "no STORE_* secrets visible — check you have admin on $REPO_SLUG"
  COUNT=$(gh secret list --repo "$REPO_SLUG" 2>/dev/null | grep -c '^STORE_' || true)
  if [[ "${COUNT:-0}" -ne 5 ]]; then
    warn "expected 5 STORE_* secrets, found ${COUNT:-0} — the job will fail fast"
    warn "with a message naming the missing ones, which is by design."
  fi
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Submit a version"
say "From here every release submits itself. This stage is for a version that"
say "shipped before the automation did."
say ""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if ! gh workflow view store-submit.yml --repo "$REPO_SLUG" >/dev/null 2>&1; then
    warn "store-submit.yml isn't on the default branch yet, so there is nothing"
    warn "to dispatch. Merge it, then:"
    note "  gh workflow run store-submit.yml --repo $REPO_SLUG -f version=X.Y.Z"
  else
    LATEST=$(gh release view --repo "$REPO_SLUG" --json tagName -q .tagName 2>/dev/null || true)
    LATEST="${LATEST#v}"
    [[ -n "$LATEST" ]] && note "Latest release: $LATEST"
    printf '  %sVersion to submit%s %s[Enter skips]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
    read -r SUBMIT_VERSION || true
    if [[ -n "${SUBMIT_VERSION:-}" ]]; then
      SUBMIT_VERSION="${SUBMIT_VERSION#v}"
      warn "This sends $SUBMIT_VERSION to certification, and from there to everyone"
      warn "who has Cadent from the Store."
      if confirm "Submit $SUBMIT_VERSION to the Microsoft Store?"; then
        gh workflow run store-submit.yml --repo "$REPO_SLUG" -f version="$SUBMIT_VERSION" \
          && printf '  %s✓%s dispatched\n' "$GREEN" "$RESET" \
          || warn "dispatch failed — trigger it from the Actions tab"
        say "Watch it with:  gh run watch --repo $REPO_SLUG"
        note "Check the run's CONCLUSION, not the watch command's exit code —"
        note "gh run watch can exit 0 on a failed run."
      fi
    fi
  fi
else
  open_url "https://github.com/$REPO_SLUG/actions/workflows/store-submit.yml"
  step "Run workflow, with the version to submit."
fi
say ""
note "The job ends when the Store accepts the submission. Certification itself"
note "takes hours to days and reports by email and in Partner Center."
pause

finish

say "Where things live from here:"
note "  Release + Store process:  docs/agents/releases.md"
note "  Submission script:        scripts/store_submit.py"
note "  Workflow:                 .github/workflows/store-submit.yml"
note "  Captured values:          $ENV_FILE (gitignored)"
printf '\n'
