#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# One-time setup: get Cadent's signed Windows installer into the Microsoft
# Store via the MSI/EXE submission path. See docs/agents/releases.md.
#
# Stage 5 (identity validation) is the long pole — Microsoft takes 1 to 20
# business days. The wizard exits cleanly there and picks up where it left off
# when you re-run it, so nothing after it has to be held open.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

REPO_SLUG="mikeallisonJS/cadent"

banner "Cadent — Microsoft Store setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "Checking the two CLIs this wizard leans on."

MISSING=0
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  printf '  %s✓%s gh is installed and authenticated\n' "$GREEN" "$RESET"
else
  warn "gh is missing or not logged in — run: gh auth login"
  note "Without it, stage 8 prints the secrets for you to paste by hand."
  MISSING=1
fi

if command -v az >/dev/null 2>&1; then
  printf '  %s✓%s az is installed\n' "$GREEN" "$RESET"
  if az account show >/dev/null 2>&1; then
    printf '  %s✓%s az is logged in\n' "$GREEN" "$RESET"
  else
    warn "az is installed but not logged in — run: az login"
    MISSING=1
  fi
else
  warn "az is missing — https://aka.ms/installazurecli"
  note "Everything az does here can also be done in the portal; the wizard says how."
  MISSING=1
fi

if [[ "$MISSING" -eq 1 ]]; then
  confirm "Continue anyway?" || { say "Fix the above and re-run."; exit 0; }
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Partner Center — developer account"
say "The Store account that will own the Cadent listing."
note "Individual developer registration is free — the old \$19 one-time fee was"
note "waived with the new onboarding flow. Don't pay for a Company account; an"
note "Individual one is the right shape for this."
open_url "https://storedeveloper.microsoft.com/"
step "Sign in with the Microsoft account you want to own the listing."
step "Choose account type: Individual."
step "Complete the identity and payout details it asks for."
step "Set your publisher display name — this is what users see under the app"
step "  name in the Store, so pick the one you want to live with."
ask MS_PUBLISHER_NAME "Publisher display name you registered:"
write_env MS_PUBLISHER_NAME "$MS_PUBLISHER_NAME"
note "Keep this tab; stage 10 comes back to Partner Center."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Azure — subscription and resource provider"
say "Artifact Signing (formerly Trusted Signing) is what signs the installer."
note "~\$10/month. This is the only recurring cost in the whole setup."
warn "Individual identity validation pulls its details from your Azure BILLING"
warn "account, and the billing account type must be Individual to match. Check"
warn "the legal name and address there are exactly what should appear on the"
warn "certificate — a mismatch means redoing validation, not editing it."
open_url "https://portal.azure.com/#view/Microsoft_Azure_Billing/SubscriptionsBladeV2"
step "Make sure you have a subscription (create a Pay-As-You-Go one if not)."
ask AZURE_SUBSCRIPTION_ID "Subscription ID:"
write_env AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"

if command -v az >/dev/null 2>&1 && az account show >/dev/null 2>&1; then
  say "Registering the Microsoft.CodeSigning provider and adding the extension."
  az account set -s "$AZURE_SUBSCRIPTION_ID" || warn "couldn't select that subscription"
  az provider register --namespace Microsoft.CodeSigning >/dev/null 2>&1 \
    && printf '  %s✓%s Microsoft.CodeSigning registering (takes a minute)\n' "$GREEN" "$RESET" \
    || warn "provider registration failed — do it in the portal under Subscriptions > Resource providers"
  az extension add --name artifact-signing >/dev/null 2>&1 \
    && printf '  %s✓%s az artifact-signing extension installed\n' "$GREEN" "$RESET" \
    || warn "couldn't add the artifact-signing extension"
else
  step "In the portal: Subscriptions > your subscription > Resource providers >"
  step "  search Microsoft.CodeSigning > Register."
fi

AZURE_TENANT_ID_VALUE=""
if command -v az >/dev/null 2>&1 && az account show >/dev/null 2>&1; then
  AZURE_TENANT_ID_VALUE=$(az account show --query tenantId -o tsv 2>/dev/null || true)
fi
if [[ -n "$AZURE_TENANT_ID_VALUE" ]]; then
  printf '  %s✓%s tenant id read from az: %s\n' "$GREEN" "$RESET" "$AZURE_TENANT_ID_VALUE"
  AZURE_SIGN_TENANT_ID="$AZURE_TENANT_ID_VALUE"
else
  step "Portal > Microsoft Entra ID > Overview > Tenant ID."
  ask AZURE_SIGN_TENANT_ID "Tenant ID:"
fi
write_env AZURE_SIGN_TENANT_ID "$AZURE_SIGN_TENANT_ID"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Azure — Artifact Signing account"
say "The container that will hold your identity validation and certificate."
warn "Public Trust certificates for INDIVIDUAL developers are only available in"
warn "the United States and Canada. Organizations have a wider list."
open_url "https://portal.azure.com/#browse/Microsoft.CodeSigning%2FcodeSigningAccounts"
step "Select Create."
step "Subscription: the one above. Resource group: create one, e.g. cadent-signing."
step "Account name: 3-24 alphanumerics, globally unique, starts with a letter."
step "Region: pick one near you — East US is the usual default."
step "Pricing: Basic is enough for one app's releases."
step "Review + create."
ask AZURE_SIGN_ACCOUNT "Artifact Signing account name:"
ask AZURE_SIGN_RESOURCE_GROUP "Resource group you put it in:"
write_env AZURE_SIGN_ACCOUNT "$AZURE_SIGN_ACCOUNT"
write_env AZURE_SIGN_RESOURCE_GROUP "$AZURE_SIGN_RESOURCE_GROUP"

say ""
say "Now the endpoint URI for that region. Signing calls go here, and it must"
say "match the region you just chose:"
note "  East US          https://eus.codesigning.azure.net"
note "  West US          https://wus.codesigning.azure.net"
note "  West US 2        https://wus2.codesigning.azure.net"
note "  West US 3        https://wus3.codesigning.azure.net"
note "  Central US       https://cus.codesigning.azure.net"
note "  North Central US https://ncus.codesigning.azure.net"
note "  South Central US https://scus.codesigning.azure.net"
note "  West Central US  https://wcus.codesigning.azure.net"
note "  (full list: https://learn.microsoft.com/azure/artifact-signing/quickstart)"
ask AZURE_SIGN_ENDPOINT "Endpoint URI for your region:"
write_env AZURE_SIGN_ENDPOINT "$AZURE_SIGN_ENDPOINT"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Azure — identity validation (the long wait)"
say "Microsoft verifies who you are before it will issue a public certificate."
warn "Portal only — this step has no CLI, and it takes 1 to 20 business days."
say ""
say "First, the role. Identity validation is invisible without it:"
step "Your Artifact Signing account > Access control (IAM) > Add role assignment."
step "Role: 'Artifact Signing Identity Verifier' — assign it to yourself."
note "You also need at least Reader at subscription scope for that role to work."
say ""
say "Then the validation itself:"
step "Account > Objects > Identity validations."
step "Switch the dropdown from Organization to Individual, then New Identity > Public."
step "Select the billing account tied to your subscription."
step "The form auto-fills from it and is read-only — if anything is wrong, fix it"
step "  in the billing account, not here."
step "Check Certificate subject preview, then Create."
step "Status goes In Progress, then Action Required — click your name and follow"
step "  'Please complete your verification here' to the AU10TIX ID check."
step "You'll need a government photo ID and a phone with a camera."
open_url "https://portal.azure.com/#browse/Microsoft.CodeSigning%2FcodeSigningAccounts"
say ""
if confirm "Is the identity validation status showing Completed?"; then
  printf '  %s✓%s identity validated\n' "$GREEN" "$RESET"
else
  say ""
  say "That's fine — this is the step that waits."
  note "Microsoft emails you when the status changes. Re-run this wizard then:"
  note "  bash scripts/store_setup_wizard.sh"
  note "Everything you've entered is saved in $ENV_FILE, so you'll be able to"
  note "press Enter through the stages above."
  finish
  exit 0
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Azure — certificate profile"
say "The profile is the logical container for the certificates you sign with."
step "Your Artifact Signing account > Objects > Certificate profiles > Create."
step "Type: Public Trust. (Public Trust Test signs, but nothing trusts it —"
step "  the Store will reject a test-signed installer.)"
step "Name: 5-100 alphanumerics, unique within the account."
step "Verified CN and O: pick the identity validation you just completed."
step "Program type: leave as None."
step "Create."
ask AZURE_SIGN_PROFILE "Certificate profile name:"
write_env AZURE_SIGN_PROFILE "$AZURE_SIGN_PROFILE"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Entra — service principal for CI"
say "GitHub Actions needs its own identity to sign with; it can't use yours."
open_url "https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
step "New registration. Name it something like 'cadent-ci-signing'."
step "Supported account types: single tenant. No redirect URI. Register."
step "On the Overview page, copy the Application (client) ID."
ask AZURE_SIGN_CLIENT_ID "Application (client) ID:"
step "Certificates & secrets > Client secrets > New client secret."
step "Copy the VALUE column, not the Secret ID — the value is shown once."
warn "Note the expiry you chose. When it lapses, signing fails and the fix is a"
warn "new secret here plus a re-run of stage 8."
ask_secret AZURE_SIGN_CLIENT_SECRET "Client secret value:"
write_env AZURE_SIGN_CLIENT_ID "$AZURE_SIGN_CLIENT_ID"
write_env AZURE_SIGN_CLIENT_SECRET "$AZURE_SIGN_CLIENT_SECRET"

say ""
say "Now grant it signing rights, scoped to the one certificate profile."
SCOPE="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${AZURE_SIGN_RESOURCE_GROUP}/providers/Microsoft.CodeSigning/codeSigningAccounts/${AZURE_SIGN_ACCOUNT}/certificateProfiles/${AZURE_SIGN_PROFILE}"
if command -v az >/dev/null 2>&1 && az account show >/dev/null 2>&1; then
  SP_OBJECT_ID=$(az ad sp show --id "$AZURE_SIGN_CLIENT_ID" --query id -o tsv 2>/dev/null || true)
  if [[ -z "$SP_OBJECT_ID" ]]; then
    say "No service principal for that app yet — creating one."
    az ad sp create --id "$AZURE_SIGN_CLIENT_ID" >/dev/null 2>&1 || true
    SP_OBJECT_ID=$(az ad sp show --id "$AZURE_SIGN_CLIENT_ID" --query id -o tsv 2>/dev/null || true)
  fi
  if [[ -n "$SP_OBJECT_ID" ]] && az role assignment create \
      --assignee-object-id "$SP_OBJECT_ID" \
      --assignee-principal-type ServicePrincipal \
      --role "Artifact Signing Certificate Profile Signer" \
      --scope "$SCOPE" >/dev/null 2>&1; then
    printf '  %s✓%s assigned Artifact Signing Certificate Profile Signer\n' "$GREEN" "$RESET"
  else
    warn "couldn't assign the role automatically — do it in the portal:"
    step "Certificate profile > Access control (IAM) > Add role assignment >"
    step "  'Artifact Signing Certificate Profile Signer' > your app registration."
    SKIPPED+=("role assignment: Artifact Signing Certificate Profile Signer on $AZURE_SIGN_PROFILE")
  fi
else
  step "Certificate profile > Access control (IAM) > Add role assignment >"
  step "  'Artifact Signing Certificate Profile Signer' > your app registration."
  note "Or, with az: az role assignment create --assignee <objectId> \\"
  note "  --role \"Artifact Signing Certificate Profile Signer\" --scope \"$SCOPE\""
  SKIPPED+=("role assignment: Artifact Signing Certificate Profile Signer on $AZURE_SIGN_PROFILE")
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub — the six signing secrets"
say "build-installer.yml reads all six or none. A partial set fails the build"
say "on purpose, so nothing ever ships half-signed."
set_secret AZURE_SIGN_TENANT_ID     "$AZURE_SIGN_TENANT_ID"
set_secret AZURE_SIGN_CLIENT_ID     "$AZURE_SIGN_CLIENT_ID"
set_secret AZURE_SIGN_CLIENT_SECRET "$AZURE_SIGN_CLIENT_SECRET"
set_secret AZURE_SIGN_ENDPOINT      "$AZURE_SIGN_ENDPOINT"
set_secret AZURE_SIGN_ACCOUNT       "$AZURE_SIGN_ACCOUNT"
set_secret AZURE_SIGN_PROFILE       "$AZURE_SIGN_PROFILE"

say ""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "What the repo has now:"
  gh secret list --repo "$REPO_SLUG" 2>/dev/null | grep AZURE_SIGN || \
    warn "no AZURE_SIGN_* secrets visible — check you have admin on $REPO_SLUG"
  COUNT=$(gh secret list --repo "$REPO_SLUG" 2>/dev/null | grep -c AZURE_SIGN || true)
  if [[ "${COUNT:-0}" -ne 6 ]]; then
    warn "expected 6 AZURE_SIGN_* secrets, found ${COUNT:-0} — the build will fail"
    warn "fast with a message naming the missing ones, which is by design."
  fi
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify — a real signed build"
say "Before touching Partner Center, prove the pipeline signs."
say "build-installer.yml signs the PyInstaller payload, compiles the Inno"
say "installer, signs that too, then checks it installs and uninstalls silently"
say "— the requirement that fails the most Store submissions."
say ""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Kick off a build now (workflow_dispatch on main)?"; then
    gh workflow run build-installer.yml --repo "$REPO_SLUG" --ref main \
      && printf '  %s✓%s dispatched\n' "$GREEN" "$RESET" \
      || warn "dispatch failed — trigger it from the Actions tab"
    say "Watch it with:  gh run watch --repo $REPO_SLUG"
  fi
else
  open_url "https://github.com/$REPO_SLUG/actions/workflows/build-installer.yml"
  step "Run workflow > Run workflow, on main."
fi
say ""
step "When it's green, check the 'Verify the signature' step's log — it prints"
step "  the certificate subject. That name is what users see in the UAC and"
step "  SmartScreen dialogs, so read it once and make sure it's right."
step "Download the artifact and install it on a real machine if you can."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Partner Center — the submission"
say "Last stage. You need a published GitHub Release to point at, so tag a"
say "release first if there isn't a signed one yet (see docs/agents/releases.md)."
open_url "https://partner.microsoft.com/dashboard/apps-and-games/overview"
step "Create a new app, reserve the name 'Cadent'."
step "Product setup: choose the MSI/EXE (unpackaged) path, not MSIX."
step "Packages: paste the direct HTTPS URL of the installer .exe asset on the"
step "  GitHub Release for the tag you're shipping."
warn "That URL must be version-specific and must never change afterwards. Every"
warn "new version is a NEW submission with a NEW URL — repointing an old one is"
warn "against Store policy."
step "Installer parameters — silent switches, which the build already exercises:"
note "    install:   /VERYSILENT /SUPPRESSMSGBOXES /NORESTART"
note "    uninstall: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART"
step "Properties: category Productivity. Declare microphone use — Cadent records"
step "  audio on a hotkey, and an undeclared mic is a certification failure."
step "Age ratings: complete the questionnaire (Cadent is a utility; it should"
step "  come out at the lowest rating)."
step "Store listing: description, at least one screenshot, and the privacy"
step "  policy URL. Lead with the fact that transcription is fully local."
say ""
warn "Disclose the GPU support pack in the description."
note "Cadent downloads two cuBLAS DLLs at runtime for optional CUDA acceleration."
note "That is executable code arriving after install, and a reviewer who finds it"
note "unannounced reads it as dynamically included code. Said plainly up front —"
note "user-initiated, disclosed in-app, optional, removable by deleting the"
note "folder — it is a feature description instead of a finding."
say ""
step "Submit for certification."
note "Certification usually lands within a few business days. Failures come back"
note "with the specific policy cited, which is fixable and resubmittable."
pause

finish

say "Where things live from here:"
note "  Release + signing process:  docs/agents/releases.md"
note "  Signing script:             scripts/sign_windows.py"
note "  Build + verify workflow:    .github/workflows/build-installer.yml"
note "  Captured values:            $ENV_FILE (gitignored)"
printf '\n'
